platform:
  - x86

environment:
  global:
    FORK_USER: ocaml
    FORK_BRANCH: master
    CYG_ROOT: C:\cygwin64
    OPAM_SWITCH: 4.07.0+mingw64c
    PINS: "index.dev:. index-bench.dev:."
  matrix:
    - PACKAGE: "index.dev"
    - PACKAGE: "index-bench.dev"

install:
  - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/$env:FORK_USER/ocaml-ci-scripts/$env:FORK_BRANCH/appveyor-install.ps1"))

build_script:
  - call %CYG_ROOT%\bin\bash.exe -l %APPVEYOR_BUILD_FOLDER%\appveyor-opam.sh